#!/usr/bin/env python3
# https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
import sys

for line in sys.stdin:
    trimmed = line.strip()
    if trimmed == "":
        print(">")
    elif trimmed.startswith(">"):
        print(trimmed)
    else:
        print("> " + trimmed)
