#!/usr/bin/env bash
# https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
set -e
set -u
set -o pipefail

yt-dlp \
  --embed-chapters \
  --embed-thumbnail \
  --extract-audio \
  --audio-format mp3 \
  -f worstaudio \
  "$@"
