#!/usr/bin/env bash
# https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
set -e
set -u
set -o pipefail

if [ "$1" == lofi ]; then
  url='https://live.hunter.fm/lofi_low'
elif [ "$1" == rock ]; then
  url='http://playerservices.streamtheworld.com/api/livestream-redirect/KINK.mp3'
elif [ "$1" == alt ]; then
  url='http://icecast.vrtcdn.be/stubru-high.mp3'
elif [ "$1" == bob ]; then
  url='http://us5.internet-radio.com:8121/listen.pls&t=.m3u'
elif [ "$1" == kfai ]; then
  url='https://kfai.broadcasttool.stream/kfai-1'
else
  echo "don't know $1" 1>&2
  exit 1
fi

exec mpv --really-quiet "$url"
