#!/usr/bin/env bash
https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
set -e
set -u
set -o pipefail

ffmpeg -i "$1" -c:v libx264 -tag:v avc1 -movflags faststart -crf "${3:-30}" -preset superfast "$2"
