#!/usr/bin/env bash
# https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
set -e
set -u

if [[ "$(uname)" == 'Darwin' ]]; then
  exec /usr/bin/osascript -e 'tell application "System Events" to sleep'
else
  systemctl suspend
fi
